### ISSUE TITLE
can you make the pages flip between stimulus?

### ISSUE THREAD

**Issue by fieldlinguist** [BilingualAphasia/AndroidBilingualAphasiaTest#8] opened 2011-10-22 18:09 UTC
we think it would look great if the pages flipped between the stimuli. that would really give it the look of virtual paper.

**Comment by fieldlinguist** [comment] 2011-10-22 18:11
could try this project

http://code.google.com/p/android-page-curl/issues/list

**Comment by cesine** [comment] 2011-10-24 13:32
that project didnt scale the images and cant handle orientation changes so they locked the orientation which is not best practice. 

found another page curl repository which appears to follow best practices, scales the image and is well maintained. 
https://github.com/harism/android_page_curl

made a few modifications (full screen images, with no border around the image) in https://github.com/cesine/android_page_curl

**Comment by cesine** [comment] 2011-10-25 00:10
its working! the fix is in this adaptation of the experiment: https://github.com/cesine/AndroidMorphologicalAwareness/blob/master/src/ca/ilanguage/oprime/morphologicalawareness/ui/StoryBookSubExperiment.java

we might also integrate it into the bilingual aphasia test in the next release so that it will be more obvious when the syntactic comprehension stimulus advance to the next stimulus which is the same picture. the problem is that any touch should advance, not just a page turning action. so we would have to try to keep the animation but activate it on any touch. that might be complicated.

**Comment by cesine** [comment] 2011-10-27 15:27
added a couple of important features:
- children/participants can touch the images and the screen wont react (coded at the moment to only turn page if the touch is within 200px of the sides. TODO make it relative to the screen size)
- play an mp3 for the sound of paper turning, just after the animation. (TODO ideally need another shorter sound for when the page falls back down and doesnt turn, need to find where in the code a hook for this sound could be added)

**Closed as completed by cesine** 2011-10-27 15:27 UTC
Labels: Programming
